#!/usr/bin/env bash
# Rebuild the embedded boot ROMs from bootrom/ and regenerate
# src/bootrom.c3 (DMG) and src/bootrom_cgb.c3 (CGB).
#
#   scripts/build-bootroms.sh
#
# Only needed after changing bootrom/: the generated .c3 files are committed.
# Needs RGBDS 1.0 (rgbasm, rgblink, rgbgfx), a C compiler and python3.
#
# DMG: bootix by Hacktix (CC0), with a "REW" logo instead of the cartridge's.
# CGB: SameBoy's boot ROM by Lior Halphon (MIT, see LICENSE-sameboy), with a
#      "REW" logo (bootrom/rew_logo.png) instead of the SameBoy and Nintendo logos.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/bootrom"
OUT="$(mktemp -d)"
trap 'rm -rf "$OUT"' EXIT

rgbasm -o "$OUT/dmg.o" "$SRC/rew_dmg.asm"
rgblink -x -o "$OUT/dmg.bin" "$OUT/dmg.o"

cc -std=c99 -O2 "$SRC/pb12.c" -o "$OUT/pb12"
# Logo colours: 0 white, 1 soft edge, 2 unused (black), 3 letters. Column-major
# tiles, all 48 kept: the tilemap loop in rew_cgb.asm expects exactly that.
rgbgfx -Z -c '#ffffff,#aaaaaa,#000000,#282828' -o "$OUT/RewLogo.2bpp" "$SRC/rew_logo.png"
"$OUT/pb12" < "$OUT/RewLogo.2bpp" > "$OUT/RewLogo.pb12"
rgbasm --include "$OUT/" --include "$SRC/" -o "$OUT/cgb.o" "$SRC/rew_cgb.asm"
rgblink -x -o "$OUT/cgb.bin" "$OUT/cgb.o"

python3 - "$OUT/dmg.bin" "$OUT/cgb.bin" "$ROOT/src" <<'EOF'
import sys

def array(data):
    return "\n".join("\t" + " ".join("0x%02X," % b for b in data[i:i + 12])
                     for i in range(0, len(data), 12))

dmg = open(sys.argv[1], "rb").read()
cgb = open(sys.argv[2], "rb").read()
assert len(dmg) == 256 and len(cgb) == 2304

open(sys.argv[3] + "/bootrom.c3", "w").write(f"""module bootrom;

// DMG boot ROM: the CC0-licensed "bootix" by Hacktix (see LICENSE-bootix),
// modified to scroll in a "REW" logo instead of the cartridge's Nintendo logo.
// Generated by scripts/build-bootroms.sh from bootrom/rew_dmg.asm.
const char[256] DMG = {{
{array(dmg)}
}};
""")

open(sys.argv[3] + "/bootrom_cgb.c3", "w").write(f"""module bootrom;

// CGB boot ROM: SameBoy's open-source boot ROM by Lior Halphon (MIT/Expat,
// see LICENSE-sameboy), modified to show a "REW" logo instead of the SameBoy
// and Nintendo logos. For DMG games it picks the compatibility palettes from
// the title like Nintendo's does. Generated by scripts/build-bootroms.sh from
// bootrom/rew_cgb.asm.
//
// 2304 bytes, mapped at $0000-$00FF and $0200-$08FF while it runs; the
// cartridge header at $0100-$01FF stays visible.
const char[2304] CGB = {{
{array(cgb)}
}};
""")
EOF
echo "rebuilt src/bootrom.c3 and src/bootrom_cgb.c3"
