#!/usr/bin/env bash
# Build wer's own boot ROMs from bootrom/ and regenerate src/bootrom.c3 (DMG)
# and src/bootrom_cgb.c3 (CGB).
#
#   scripts/build-bootroms.sh
#
# Only needed after changing bootrom/: the generated .c3 files are committed.
# Needs RGBDS 1.0 (rgbasm, rgblink, rgbgfx) and python3.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/bootrom"
OUT="$(mktemp -d)"
trap 'rm -rf "$OUT"' EXIT

# DMG logo: ASCII art -> a nibble per 4-pixel row, 2 bytes per 4x4 tile,
# the top row of tiles first (the boot ROM doubles every pixel).
python3 - "$SRC/wer_logo_dmg.txt" "$OUT/wer_logo_dmg.inc" <<'EOF'
import sys
rows = [l.rstrip("\n") for l in open(sys.argv[1]) if l.strip()]
assert len(rows) == 8 and all(len(r) == 32 for r in rows)
def nibble(r, c):
    return int(rows[r][4 * c:4 * c + 4].replace("#", "1").replace(".", "0"), 2)
data = []
for half in range(2):
    for c in range(8):
        data.append(nibble(4 * half, c) << 4 | nibble(4 * half + 1, c))
        data.append(nibble(4 * half + 2, c) << 4 | nibble(4 * half + 3, c))
open(sys.argv[2], "w").write("    db " + ", ".join("$%02X" % b for b in data) + "\n")
EOF

# CGB letters: 1 bit per pixel, 8-pixel columns top to bottom (-Z); each
# 40-pixel letter keeps only its non-blank columns (LetterInfo).
rgbgfx -d 1 -Z -c '#ffffff,#000000' -o "$OUT/wer_letters.1bpp" "$SRC/wer_letters.png"
python3 - "$OUT/wer_letters.1bpp" "$OUT/wer_letters.inc" <<'EOF'
import sys
d = open(sys.argv[1], "rb").read()
assert len(d) == 3 * 5 * 24
info, data = [], []
for letter in range(3):
    cols = [c for c in range(5) if any(d[(letter * 5 + c) * 24:(letter * 5 + c + 1) * 24])]
    first, last = cols[0], cols[-1]
    info.append(f"    dw LetterData{letter}\n    db {first}, {last - first + 1}")
    data.append(f"LetterData{letter}:")
    for c in range(first, last + 1):
        col = d[(letter * 5 + c) * 24:(letter * 5 + c + 1) * 24]
        data.append("    db " + ", ".join("$%02X" % b for b in col))
open(sys.argv[2], "w").write("; Per letter: its columns, the first box column they go in, how many.\n"
    "LetterInfo:\n" + "\n".join(info) + "\n" + "\n".join(data) + "\n")
EOF

rgbasm -I "$OUT/" -I "$SRC/" -o "$OUT/dmg.o" "$SRC/wer_dmg.asm"
rgblink -x -o "$OUT/dmg.bin" "$OUT/dmg.o"
rgbasm -I "$OUT/" -I "$SRC/" -o "$OUT/cgb.o" "$SRC/wer_cgb.asm"
rgblink -x -o "$OUT/cgb.bin" "$OUT/cgb.o"

python3 - "$OUT/dmg.bin" "$OUT/cgb.bin" "$ROOT/src" <<'EOF'
import sys

def array(data):
    return "\n".join("\t" + " ".join("0x%02X," % b for b in data[i:i + 12])
                     for i in range(0, len(data), 12))

dmg = open(sys.argv[1], "rb").read()
cgb = open(sys.argv[2], "rb").read()
assert len(dmg) == 256, len(dmg)
assert len(cgb) <= 2304, len(cgb)
cgb = cgb.ljust(2304, b"\0")

open(sys.argv[3] + "/bootrom.c3", "w").write(f"""module bootrom;

// wer's DMG boot ROM: WER logo, chime, the original's hand-over registers.
// Generated by scripts/build-bootroms.sh from bootrom/wer_dmg.asm.
const char[256] DMG = {{
{array(dmg)}
}};
""")

open(sys.argv[3] + "/bootrom_cgb.c3", "w").write(f"""module bootrom;

// wer's CGB boot ROM: WER logo with a rainbow, chime, and for monochrome games
// the compatibility palettes and DMG mode a Game Boy Color sets up.
// Generated by scripts/build-bootroms.sh from bootrom/wer_cgb.asm.
//
// 2304 bytes, mapped at $0000-$00FF and $0200-$08FF while it runs; the
// cartridge header at $0100-$01FF stays visible.
const char[2304] CGB = {{
{array(cgb)}
}};
""")
print(f"DMG boot ROM: 256 bytes; CGB boot ROM: {len(open(sys.argv[2], 'rb').read())} of 2304 bytes used")
EOF
echo "rebuilt src/bootrom.c3 and src/bootrom_cgb.c3"
